{{- range .Values.topics }}
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: {{ include "kafka.topicResourceName" .name }}
  labels:
    strimzi.io/cluster: {{ $.Values.cluster.name }}
spec:
  topicName: "{{ .name }}"
  partitions: {{ .partitions | default $.Values.topicDefaults.partitions }}
  replicas: {{ .replicas | default $.Values.topicDefaults.replicas }}
  config:
{{ toYaml ( .config | default $.Values.topicDefaults.config ) | indent 4 }}
---
{{- end }}

