apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-brokers-metrics
  labels:
    app: strimzi
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      strimzi.io/cluster: kafka
      strimzi.io/name: kafka-kafka
  podMetricsEndpoints:
    - path: /metrics
      port: tcp-prometheus
      interval: 30s
      honorLabels: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_cluster]
          targetLabel: kafka_cluster
        - sourceLabels: [__meta_kubernetes_pod_label_strimzi_io_name]
          targetLabel: kafka_pod

