apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: kafka
spec:
  podSelector:
    matchLabels:
      strimzi.io/cluster: {{ .Values.cluster.name }}
      strimzi.io/name: {{ .Values.cluster.name }}-kafka
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 9092
    - from:
        - podSelector:
            matchLabels:
              strimzi.io/cluster: {{ .Values.cluster.name }}
              strimzi.io/name: {{ .Values.cluster.name }}-kafka
      ports:
        - protocol: TCP
          port: 9094

