apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: strimzi-cluster-operator-metrics
  labels:
    app: strimzi
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      name: strimzi-cluster-operator
  podMetricsEndpoints:
    - path: /metrics
      port: http
      interval: 30s
      honorLabels: true
